//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Resources.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EMAIL_MESSAGES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EMAIL_MESSAGES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Resources.Core.Messages.EMAIL_MESSAGES", typeof(EMAIL_MESSAGES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para confirmar o cadastro de sua conta, favor clique no link: &lt;a href=&apos;{URL_ACCOUNT_CONFIRMATION}&apos;&gt;Confirmar minha conta&lt;/a&gt;.
        /// </summary>
        public static string ACCOUNT_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este é um e-mail de notificação de ativação da sua conta em nosso sistema, caso esta ativação não tenha sido feita por você, favor entrar em contato com o nosso suporte..
        /// </summary>
        public static string ACCOUNT_CONFIRMATION_NOTIFICATION_MESSAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_CONFIRMATION_NOTIFICATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Ativação de Conta.
        /// </summary>
        public static string ACCOUNT_CONFIRMATION_NOTIFICATION_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_CONFIRMATION_NOTIFICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Conta.
        /// </summary>
        public static string ACCOUNT_CONFIRMATION_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_CONFIRMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este é um e-mail de confirmação da alteração de sua senha, caso esta alteração não tenha sido feita por você, favor entrar em contato com o suporte, ou altere sua senha novamente, clicando no link: &lt;a href=&apos;{URL_RESET_PASSWORD}&apos;&gt;Redefinir senha&lt;/a&gt;.
        /// </summary>
        public static string ACCOUNT_RESET_PASSWORD_NOTIFICATION_MESSAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_RESET_PASSWORD_NOTIFICATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação de Redefinição de Senha.
        /// </summary>
        public static string ACCOUNT_RESET_PASSWORD_NOTIFICATION_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_RESET_PASSWORD_NOTIFICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para redefinir a senha de sua conta, favor clique no link: &lt;a href=&apos;{URL_RESET_PASSWORD}&apos;&gt;Redefinir senha&lt;/a&gt;.
        /// </summary>
        public static string ACCOUNT_RESET_PASSWORD_SOLICITATION_MESSAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_RESET_PASSWORD_SOLICITATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinir Senha.
        /// </summary>
        public static string ACCOUNT_RESET_PASSWORD_SOLICITATION_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_RESET_PASSWORD_SOLICITATION_TITLE", resourceCulture);
            }
        }
    }
}
